---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# PrésiData 2022
 
This repository lists websites or other repository, which provide raw data or data analysis related to the 2022 French presidential elections.

## Data Sources

#### Polls

[`NSPPolls`](https://github.com/nsppolls/nsppolls) collects all published polls. 

#### Speaking time of candidates

[`csatimer`](https://github.com/benjaminguinaudeau/csatimer) proposes a machine-readable version of the data published by the [csa](https://www.csa.fr/csapluralisme/tableau). It contains data on how much each candidat and its support spoke in the main national French media.

#### Manifestos

The folder [`manifesto`](https://github.com/benjaminguinaudeau/presidata2022/tree/master/manifesto) contains the manifestos of the most important candidates. 

#### Sponsorship

The list of local sponsors supporting the candidates, published by the French constituional council and updated twice a week can be found [here](https://presidentielle2022.conseil-constitutionnel.fr/les-parrainages/tous-les-parrainages-valides.html)

## Dashboards

#### Comparing candidates' proposals

The [décodeurs](https://www.lemonde.fr/les-decodeurs/) from Le Monde propose a [dashboard](https://www.lemonde.fr/les-decodeurs/article/2022/02/16/election-presidentielle-2022-comparez-les-programmes-des-principaux-candidats_6113964_4355770.html) to compare the proposal of the candidates. 

The underlying data is available in the tabular format [here](https://github.com/benjaminguinaudeau/presidata2022/tree/master/data_dump/decodeurs_programmes_candidats.csv).


#### Candidates' sponsorship

To confirm their candidacy, candidates to the French presidential elections need to be sponsored by at least 500 local elected officials. The [décodeurs](https://www.lemonde.fr/les-decodeurs/article/2022/02/01/election-presidentielle-2022-visualisez-les-parrainages-obtenus-par-les-candidats_6111902_4355770.html) tracks down how many sponsors each candidate received. 

#### Electoral pledges from 2017

On [luipresident.fr](https://www.luipresident.fr/), journalists listed all pledges formulated by Macron during the previous election. For each pledge, they coded whether it was fullfilled and commented the state of fullfillment. 








