---
title: "twitter"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(academictwitteR)

fix_date <- function(x) paste0(str_replace(as.character(lubridate::as_datetime(x) + 1), "\\s", "T"), "Z")
```

1. Tweets officiels
2. Réponses aux tweets
3. Mentions




```{r}
inp <- bind_rows(
  tibble::tibble(cand = "Macron", perso = "EmmanuelMacron", parti = "enmarchef", soutien = "Macron2022r", hashtag = list(c("#avecvous2022"))),
  tibble::tibble(cand = "Hidalgo", perso = "Anne_Hidalgo", parti = "partisocialiste", soutien = "2022avecHidalgo", hashtag = list(c("#Hidalgo2022"))),
  tibble::tibble(cand = "Jadot", perso = "yjadot", parti = "EELV", soutien = "2022lecologie", hashtag = list(c("#Jadot2022", "#2022lecologie"))),
  tibble::tibble(cand = "Mélenchon", perso = "JLMelenchon", parti = "FranceInsoumise", soutien = "Melenchon_2022", hashtag = list(c("#Mélenchon2022", "#UnionPopulaire,",  "#DynamiqueMelenchon"))),
  tibble::tibble(cand = "Pécresse", perso = "vpecresse", parti = "lesRepublicains", soutien = "avecValerie", hashtag = list(c("#Pecresse2022"))),
  tibble::tibble(cand = "Le Pen", perso = "MLP_officiel", parti = "RNational_off", soutien = "avec_marine", hashtag = list(c("#MLaFrance", "#Marine2022"))),
  tibble::tibble(cand = "Zemmour", perso = "ZemmourEric", parti = "Reconquete2022", soutien = NA_character_, hashtag = list(c("#DynamiqueZemmour", "#GenerationZemmour", "#Zemmour2022"))),
  tibble::tibble(cand = "Taubira", perso = "ChTaubira", parti = NA_character_, soutien = NA_character_, hashtag = list(c("#AvecTaubira", "#Taubira2022")))
) %>%
  mutate(across(c(perso, parti, soutien), ~paste0("@", .x))) %>%
  mutate(query = paste(cand, paste0("to:", str_remove(perso, "@")), perso, parti, soutien, hashtag %>% map_chr(paste, collapse = " OR "), sep = " OR ")) %>%
  glimpse


n_tweets <- expand_grid(query = inp$query, start = lubridate::today() - 1:10*31) %>%
  split(1:nrow(.)) %>%
  map_dfr(~{
    glimpse(.x)
    academictwitteR::count_all_tweets(query = .x$query,
                                      start_tweets = fix_date(.x$start), 
                                      end_tweets = fix_date(.x$start + 31)) %>%
      mutate(query = .x$query)
  })

write_rds(n_tweets, "n_tweets_2021.rds")

ks <- function (x){ 
  scales::number_format(accuracy = 1,
                        scale = 1/1000,
                        suffix = "k",
                        big.mark = ",")(x) 
}

sum(n_tweets$tweet_count)
```

```{r}
n_tweets %>%
  mutate(query = query$query) %>%
  left_join(inp) %>%
  mutate(date = lubridate::as_datetime(start)) %>%
  filter(tweet_count > 10) %>%
  ggplot(aes(x = date, y = tweet_count, color = cand)) +
  geom_line() +
  scale_y_continuous(labels = ks) +
  tidyquant::theme_tq() +
  labs(y = "# Tweets mentioning the candidate", x = "", color = "")

n_tweets %>%
  mutate(query = query$query) %>%
  left_join(inp) %>%
  mutate(date = lubridate::as_datetime(start)) %>%
  filter(tweet_count > 10) %>%
  ggplot(aes(x = date, y = tweet_count, color = cand)) +
  geom_line() +
  scale_y_continuous(labels = ks) +
  tidyquant::theme_tq() +
  scale_y_log10() +
  labs(y = "# Tweets mentioning the candidate", x = "", color = "")
```



```{r, fig.width = 12, fig.height = 7}
n_tweets %>%
  mutate(query = query$query) %>%
  left_join(inp) %>%
  mutate(date = lubridate::as_datetime(start)) %>%
  ggplot(aes(x = date, y = tweet_count, color = cand)) +
  geom_line() +
  facet_wrap(~cand, scales = "free", ncol = 2) +
  scale_y_continuous(labels = ks) +
  tidyquant::theme_tq() +
  labs(y = "# Tweets mentioning the candidate", x = "", color = "")

```

## All tweets from the candidates

```{r}
tweets_perso <- expand_grid(query = paste0("from:", str_remove(inp$perso, "@")), start = lubridate::today() - 1:10*31) %>%
  split(1:nrow(.)) %>%
  map_dfr(~{
    glimpse(.x)
    academictwitteR::get_all_tweets(query = .x$query, n = 10000, 
                                    start_tweets = fix_date(.x$start), 
                                    end_tweets = fix_date(.x$start + 31)) %>%
      mutate(perso = .x$query)
  })

write_rds(tweets_perso, "tweets_perso_2021.rds")
```


```{r}
tweets_perso %>%
  left_join(inp) %>%
  count(perso, source)
  
  
  
tweets_perso %>%
  left_join(inp) %>%
  unnest(public_metrics) %>%
  mutate(perso = fct_reorder(perso, like_count)) %>%
  select(perso, contains("count")) %>%
  pivot_longer(-perso) %>% 
  group_split(name) %>%
  map(~{
    .x %>%
      ggplot(aes(x = perso, y = value)) +
      geom_boxplot(outlier.size = -1) +
      coord_flip() +
      facet_wrap(~name, scales = "free") +
      scale_y_continuous(limits = quantile(.x$value, c(0.1, 0.9))) +
      theme_minimal()
  }) %>%
  patchwork::wrap_plots()
ylim(c(0, 6000))

```



